# @name Signup
POST {{baseUrl}}/{{ver}}/auth/sign-up
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "M.d. A. Apu",
  "email": "apuatcfbd@gmail.com",
  "password": "1234"
}

###

# @name Signin
POST {{baseUrl}}/{{ver}}/auth/sign-in
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "apuatcfbd@gmail.com",
  "password": "1234"
}
> {% client.global.set('token', response.body.d.token) %}

###

# @name Auth user
GET {{baseUrl}}/{{ver}}/auth/me
Authorization: Bearer {{token}}

###

# @name Signout
POST {{baseUrl}}/{{ver}}/auth/sign-out
Authorization: Bearer {{token}}

> {% client.global.set('token', '') %}

###